/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2016-2017, Linaro Limited
 * All rights reserved.
 */
#ifndef TA_GPT_H
#define TA_GPT_H

#define TA_GPT_UUID \
	{ 0x395c3b47, 0x1fc8, 0x4443, \
		{ 0x9d, 0x99, 0xb8, 0xcf, 0x6d, 0xee, 0x99, 0x7c} }

/* TODO: TA函数ID */
#define TA_GPT_CMD_LOAD_PARAMS 0
#define TA_GPT_CMD_ENCODER_FORWARD 1
#define TA_GPT_CMD_ENCODER_OUTPUT 2
#define TA_GPT_CMD_SOFTMAX_FORWARD 3
#define TA_GPT_CMD_SOFTMAX_OUTPUT 4
#define TA_GPT_CMD_LOAD_LNFWB 5
#define TA_GPT_CMD_LAYERNORM_FORWARD 6
#define TA_GPT_CMD_LAYERNORM_OUTPUT 7

#define TA_GPT_CMD_LOAD_QKVW 8
#define TA_GPT_CMD_LOAD_QKVB 9
#define TA_GPT_CMD_LOAD_LN1W 10
#define TA_GPT_CMD_LOAD_LN1B 11
#define TA_GPT_CMD_LOAD_ATTPROJW 12
#define TA_GPT_CMD_LOAD_ATTPROJB 13
#define TA_GPT_CMD_LOAD_LN2W 14
#define TA_GPT_CMD_LOAD_LN2B 15
#define TA_GPT_CMD_LOAD_FCW 16
#define TA_GPT_CMD_LOAD_FCB 17
#define TA_GPT_CMD_LOAD_FCPROJW 18
#define TA_GPT_CMD_LOAD_FCPROJB 19

#define TA_GPT_CMD_LN1_FORWARD 20
#define TA_GPT_CMD_QKV_FORWARD 21
#define TA_GPT_CMD_ATTENTION_FORWARD 22
#define TA_GPT_CMD_ATTPROJ_FORWARD 23
#define TA_GPT_CMD_RESIDUAL2_FORWARD 24
#define TA_GPT_CMD_LN2_FORWARD 25
#define TA_GPT_CMD_FC_FORWARD 26
#define TA_GPT_CMD_GELU_FORWARD 27
#define TA_GPT_CMD_FCPROJ_FORWARD 28
#define TA_GPT_CMD_RESIDUAL3_FORWARD 29
#define TA_GPT_CMD_BLOCK_OUTPUT 30

#endif /*TA_GPT_H*/
